{% set version = "0.1.1" %}

package:
  name: pycrdt-store
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pycrdt-store/pycrdt_store-{{ version }}.tar.gz
  sha256: e89a6862747ea484639ea8249b68c01e0053389c0c57721383aae86eb310db27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - anyio >=3.6.2,<5
    - sqlite-anyio >=0.2.3,<0.3.0
    - pycrdt >=0.12.13,<0.13.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pycrdt.store
  commands:
    - pip check

about:
  home: https://github.com/y-crdt/pycrdt-store
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Persistent storage for pycrdt

extra:
  recipe-maintainers:
    - davidbrochart
